#lang sicp
(define (make-account balance pass)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        ("Insufficient Funds")))
  (define (deposit amount)
    (begin (set! balance (+ balance amount))
           balance))
  (define (dispatch input-pass m)
    (cond ((not (eq? input-pass pass)) (error "INCORRECT PASSWORD"))
          ((eq? m `withdraw) withdraw)
          ((eq? m `deposit) deposit)
          (else (error "Unknown request: MAKE-ACCOUNT" m))))
  dispatch)

(define (make-joint acc old-pass new-pass)
  (define (dispatch input-pass m)
    (cond ((or (eq? input-pass old-pass) (eq? input-pass new-pass)) (acc old-pass m))
          (else (error "INCORRECT PASSWORD"))))
  dispatch)

(define peter-acc (make-account 500 `pass))
(define paul-acc (make-joint peter-acc `pass `pass1))
((paul-acc `pass1 `withdraw) 50)
((paul-acc `pass `withdraw) 50)
((peter-acc `pass `withdraw) 50)