#lang sicp
(define (neq a b) (if (eq? a b) #f #t))
(define (make-account balance secret-password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch input-password m)
    (cond ((neq secret-password input-password) (error "Incorrect Password"))
          ((eq? m `withdraw) withdraw)
          ((eq? m `deposit) deposit)
          (else (error "Unknown request: MAKE-ACCOUNT" m))))
  dispatch)

(define acc (make-account 100 `abra))
((acc `abra `withdraw) 40)
((acc `aba `withdraw) 40)