#lang sicp
(define (call-the-cops) (error "Your case is being reported to a fake police"))
(define (neq a b) (if (eq? a b) #f #t))
(define (make-account balance secret-password)
  (define inc-counter 0)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch input-password m)
    (cond ((neq secret-password input-password)
           (begin (set! inc-counter (+ inc-counter 1))
                  (if (>= inc-counter 5) (call-the-cops) (error "Incorrect Password"))))
          (else (begin (set! inc-counter 0)
                       (cond ((eq? m `withdraw) withdraw)
                             ((eq? m `deposit) deposit)
                             (else (error "Unknown request: MAKE-ACCOUNT" m)))))))
  dispatch)

(define acc (make-account 100 `abra))
((acc `abra `withdraw) 40)
((acc `aba `withdraw) 40)